application:
  subdomain: xyops
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://xyops:5522/
services:
  xyops:
    # ghcr.io/pixlcore/xyops:v1.0.9
    # upstream: ghcr.io/pixlcore/xyops:v1.0.82
    image: registry.lazycat.cloud/czyt/pixlcore/xyops:61a0f8dba5910898
    environment:
      - TZ={{.U.tz}}
      - XYOPS_xysat_local=true
      - XYOPS_satellite__config__host=${LAZYCAT_APP_DOMAIN}
      - XYOPS_satellite__config__secure=true
    binds:
      - /lzcapp/var/data:/opt/xyops/data
      - /lzcapp/var/conf:/opt/xyops/conf
    cpu_shares: 512
    mem_limit: 512M
