package: community.lazycat.app.xyops
version: 1.0.81
name: xyOps
description: "A complete workflow automation and server monitoring system"
min_os_version: 1.5.0
license: MIT
homepage: https://github.com/pixlcore/xyops
author: PixlCore
locales:
  en:
    name: "xyOps"
    description: "A complete workflow automation and server monitoring system"
  zh:
    name: "xyOps"
    description: "完整的工作流自动化和服务器监控系统"
